Revit 2022 for DUI3
specklesystems/speckle-sharp-connectors pull request #13
Opened 2024-07-10 13:02 UTC by adamhathcock

2022 loads

https://spockle.atlassian.net/browse/DUI3-395

2024-07-11 10:39 UTC, BovineOx requested changes
Not much really, request to not lose sight of changing the URL back and mostly questions around whether we can have pre-processor directives of REVIT_2022_ONWARDS or something, I think this was the previous suggestion but a) not mandatory, just maybe the right time to do it and b) @AlanRynne should weigh-in

I just stops having to faff and extra lines in places, but the !<this version> && !<that version> clearly works

2024-07-11 10:39 UTC, BovineOx commented on Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
> +#if !REVIT2020 && !REVIT2021 && !REVIT2022
We were talking about being able to say - is this 2022 onwards for instance, to simplify this

2024-07-11 10:39 UTC, BovineOx commented on Converters/Revit/Speckle.Converters.Revit2022.DependencyInjection/RevitConverterModule.cs
We need separate files/projects? I guess it's not a huge amount but I worry if DI is forgotten across versions that would be common to all

2024-07-11 10:39 UTC, BovineOx commented on DUI3/Speckle.Connectors.DUI/Url.cs
> +  public static readonly Uri Netlify = new("https://6671ddd20235b90008dbc453--boisterous-douhua-e3cefb.netlify.app/");
Is this no longer in he XAML at all? We will need to be careful not to accidentally take this forever. Does @oguzhankoral have  aticket now for fixing the CEF 60 something support? If so can we have a subtask and drop it here to update the URL back to the right one plz?

2024-07-11 10:43 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.Revit2022.DependencyInjection/RevitConverterModule.cs
We have to have new projects and refs....the DI project is not really used (I'd like to remove it and the concept) but is needed for now...was working on a shared project for it to keep everything in sync

2024-07-11 11:02 UTC, BovineOx commented on Converters/Revit/Speckle.Converters.Revit2022.DependencyInjection/RevitConverterModule.cs
The DI projects were an effort to keep DI concepts outside of things like conversion so we're aren't pushing Autofac on people, so they probably should continue to exist

2024-07-12 06:08 UTC, AlanRynne commented on Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
> +#if !REVIT2020 && !REVIT2021 && !REVIT2022
We do have this in RHINO, following the standard pattern used for c# frameworks: `RHINO7_OR_GREATER`.

I really suggest we do this bc it allows for setting lower/upper bounds without having to explicitly state all versions.

2024-07-16 08:53 UTC, BovineOx approved these changes

2024-07-16 08:53 UTC, BovineOx commented on Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
> +    // TODO: Need to figure it out equivalent of SelectionChanged for Revit2022
remove POC: add ticket to DUI3 project and link here for investigate solution for 2022

2024-07-16 08:53 UTC, BovineOx commented on Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/RevitConnectorModule.cs
> +    // POC: different versons for different versions of CEF
if this is just as is, we can remove the POC: portion of comment

2024-07-16 08:53 UTC, BovineOx commented
Just add the ticket URL for selection change

2024-07-16 09:21 UTC, adamhathcock commented on Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
> +    // TODO: Need to figure it out equivalent of SelectionChanged for Revit2022
https://spockle.atlassian.net/browse/CNX-9874

2024-07-16 10:23 UTC, merged