Agis separate dataset creation
specklesystems/speckle-sharp-connectors pull request #170
Opened 2024-08-20 02:52 UTC by KatKatKateryna

Refactoring HostObjectBuilder to treat all features individually, including GisFeatures. 
This allows to treat them in the same way in the steps of grouping into layers and Writing to datasets.
This also resolves the issue of the Map being stuck with the outdated dataset representation even after receiving the new version and overwriting it (because now we return back to main thread after clearing old datasets)

2024-08-22 09:14 UTC, adamhathcock requested changes
I didn't read everything in detail but there should probably be some optimization when using collections and Linq to avoid slowness.

I'm enjoying the usage of Interfaces and DI!

2024-08-22 09:14 UTC, adamhathcock commented on Converters/ArcGIS/Speckle.Converters.ArcGIS3/ToHost/TopLevel/GisMultipatchFeatureToHostConverter.cs
> +    List<SGIS.PolygonGeometry3d> polygonGeometry = target
Not sure this is the most optimial usage.  ToList is expensive.

Probably can just loop once over the target.geometry and switch on pattern matching casts to do a count.

2024-08-22 09:14 UTC, adamhathcock commented on Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/CharacterCleaner.cs
> +[GenerateAutoInterface]
Nice!

2024-08-22 15:09 UTC, adamhathcock submitted a review, later dismissed

2024-08-26 07:55 UTC, AlanRynne approved these changes
Kat ran me through the functionality changes on friday, and I see no glaring issues code-wise either 🙂

2024-08-26 07:55 UTC, merged