feat(revit): CNX-188 extract material quantities out for all objects
specklesystems/speckle-sharp-connectors pull request #184
Opened 2024-08-21 15:06 UTC by clairekuang

Adds material quantities to all revit objects.

This is done by mirroring behavior in V2, by:
- converting material quantities per element
- converting and caching material per material quantity

However, for post-september release we should seriously consider sending `MaterialProxies` instead of attached the material to every material quantity. Need to validate how this affect data workflows in powerbi, viewer, and excel.

2024-08-22 11:53 UTC, oguzhankoral commented on Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/MaterialQuantitiesToSpeckle.cs
> +  private static DB.Material? GetMEPSystemRevitMaterial(DB.Element e)
private static?

2024-08-26 15:48 UTC, didimitrie approved these changes

2024-08-26 16:24 UTC, oguzhankoral requested changes
minors

2024-08-26 16:24 UTC, oguzhankoral commented on Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/MaterialQuantitiesToSpeckle.cs
> +  private readonly DisplayValueExtractor _displayValueExtractor;
seems like these dudes shouldn't be injected at all

2024-08-26 16:24 UTC, oguzhankoral commented on Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/MaterialQuantitiesToSpeckle.cs
> +  /// <returns></returns>
nice doc
jokes aside, it might be good to explain why it is list of dict as key string as value object?

2024-08-26 16:37 UTC, oguzhankoral approved these changes

2024-08-26 16:37 UTC, merged