chore(revit): adds units to object params
specklesystems/speckle-sharp-connectors pull request #280
Opened 2024-09-25 10:48 UTC by clairekuang

Pulls the units from the parameter definition to add to object parameters. If no units are present, there will be no unit field on the object param.

https://latest.speckle.systems/projects/3f895e614f/models/7367fe3688
![image](https://github.com/user-attachments/assets/b954080b-6c2c-40ac-94df-a12e725c6837)

2024-09-25 16:39 UTC, oguzhankoral approved these changes
Code-wise ok to me, but can't say (yet) anything about expected behavior for this.

2024-09-27 10:16 UTC, didimitrie requested changes
@clairekuang could we do a very fast performance benchmark on this before we merge? 
basically delete the data.db from appdata/speckle, and send the advanced sample model (should be enough) with and without units on each parameter.

it should be fine overall, but i'd want to quantify what we're sacrificing in terms of performance! 

code wise everything ok!

2024-09-27 13:26 UTC, clairekuang commented
> @clairekuang could we do a very fast performance benchmark on this before we merge? basically delete the data.db from appdata/speckle, and send the advanced sample model (should be enough) with and without units on each parameter.
> 

Tested on the sample structural model, adding units was about a 5.6% increase in size :0
![image](https://github.com/user-attachments/assets/677bde31-fdf9-4dcd-8dc9-78019db00444)
commit with units: https://latest.speckle.systems/projects/3f895e614f/models/7367fe3688@e30926e581

2024-09-27 14:58 UTC, didimitrie approved these changes

2024-09-27 14:58 UTC, merged