Refactor usage of exceptions in converters/connectors
specklesystems/speckle-sharp-connectors pull request #286
Opened 2024-09-27 10:51 UTC by AlanRynne

> [!WARNING]  
> THIS IS A DRAFT!! DO NOT MERGE
> It is still pending some moving of the exceptions into the SDK repo instead, but in general the shape would remain the same.

These are the existing exceptions right now:

- SpeckleException
- ConversionNotSupportedException
- ConversionException
- UnitNotSupportedException
- ValidationException

Connectors now use exclusively `SpeckleException` instead of a mix of that and conversionexceptions.

The only place where `ConversionNotSupported` is expected is within a `RootObjectConverter`.

`ValidationException` is thrown if we can verify the data is wrong BEFORE we can attempt conversion
`ConversionException` should be used for anything else.

We can expand the types more as we find more use-cases to unify.

2024-10-10 07:24 UTC, adamhathcock requested changes
I think I follow everything...just making sure about some comments

2024-10-10 07:24 UTC, adamhathcock commented on Converters/Civil3d/Speckle.Converters.Civil3dShared/Civil3dRootToHostConverter.cs
> -    if (target is CDB.Entity civilEntity)
intentional?

2024-10-10 07:24 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueSetter.cs
>          else
I think this fine?

2024-10-10 07:24 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.RevitShared/RevitRootToHostConverter.cs
> -    if (geometryObjects.Count == 0)
is removing this okay?  Should we check for Any?

2024-10-10 07:24 UTC, adamhathcock commented on Directory.Build.props
> +    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
I think we intentionally removed this?

2024-10-10 07:24 UTC, adamhathcock commented on Sdk/Speckle.Converters.Common/Registration/ConverterManager.cs
> +  public T ResolveConverter(Type type, bool recursive = false)
Righteous

2024-10-10 09:42 UTC, KatKatKateryna commented
Tested in ArcGIS:

- [ ] SpeckleException
- [X] ConversionNotSupportedException
- [X] ConversionException
- [X] UnitNotSupportedException
- [ ] ValidationException

2024-10-10 09:53 UTC, KatKatKateryna commented on Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/FeatureClassUtils.cs
> +          throw new ValidationException("Feature Class element had no converted geometry");
possibly we can replace some of the ArgumentExceptions in other converters to ValidationException too

2024-10-16 09:21 UTC, JR-Morgan approved these changes

2024-10-16 10:01 UTC, merged