add curve to direct shape conversions
specklesystems/speckle-sharp-connectors pull request #37
Opened 2024-07-16 22:43 UTC by connorivy

## Description & motivation

## Changes:

Adds a top level converter for each ICurve implementation. I think it has to be done this way since our conversions our found by the name of the type as opposed to the actual type with implemented interface information.

## To-do before merge:

## Screenshots:

![image](https://github.com/user-attachments/assets/aa679654-5f4b-4570-9e33-081b342bc693)

## Validation of changes:

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-07-17 06:37 UTC, adamhathcock requested changes

2024-07-17 06:37 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.RevitShared/ToHost/TopLevel/ToDirectShape/ICurveToDirectShapeConverterToHostBase.cs
> +public abstract class ICurveToDirectShapeConverterToHostBase<TCurve>
Base class shouldn't begin with an I though I know why you did it

2024-07-18 07:06 UTC, adamhathcock approved these changes

2024-07-18 21:57 UTC, connorivy commented
@adamhathcock the build is failing due to xml comments that haven't been updated. Old xml comments that this pr doesn't touch. Do you know why this is happening?

2024-07-19 07:00 UTC, adamhathcock commented
XML comment restrictions got turned on.  I've got like 3 PRs with the same issue.  I'll fix yours and merge it

2024-07-19 07:02 UTC, adamhathcock approved these changes

2024-07-19 12:06 UTC, merged