receive colors with fallback conversions
specklesystems/speckle-sharp-connectors pull request #408
Opened 2024-11-25 20:28 UTC by KatKatKateryna

2024-11-26 16:27 UTC, clairekuang requested changes
Instead of passing the entire object, would be cleaner to pass the applicationId string instead

2024-11-27 09:44 UTC, oguzhankoral requested changes

2024-11-27 14:50 UTC, oguzhankoral approved these changes

2024-11-27 14:57 UTC, oguzhankoral approved these changes

2024-11-27 14:58 UTC, clairekuang approved these changes

2024-11-27 14:58 UTC, merged