Introduce Event aggregator
specklesystems/speckle-sharp-connectors pull request #417
Opened 2024-11-28 16:47 UTC by adamhathcock

https://www.notion.so/speckle/Event-Aggregation-174b78fc7aa6806a86e7f451fa7c4b96

Decouples exception handler from browser bridge.
IdleManager is now a OneTime event with IDs.
Rhino is converted.
Global Events (Doc changed) are converted.

More events to come!

2025-01-20 16:33 UTC, JR-Morgan requested changes
Changes requested on https://github.com/specklesystems/speckle-sharp-connectors/pull/505

2025-01-21 08:35 UTC, dogukankaratas commented on Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSelectionBinding.cs
> +using Speckle.Connectors.RhinoShared;
Why do we importing from RhinoShared in Tekla?

2025-01-21 10:46 UTC, adamhathcock commented
Probably done at the same time: https://github.com/specklesystems/speckle-sharp-connectors/pull/505

2025-01-21 10:50 UTC, adamhathcock commented on Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSelectionBinding.cs
> +using Speckle.Connectors.RhinoShared;
The events were declared in the wrong namespace but fixed in another PR: https://github.com/specklesystems/speckle-sharp-connectors/pull/505/commits/b5871d5fbda34a0e295971068eb3402a02971706

2025-01-21 14:13 UTC, JR-Morgan approved these changes

2025-01-21 14:20 UTC, merged