Dimitrie/cnx 855 rhino changing a material does not invalidate the objects
specklesystems/speckle-sharp-connectors pull request #421
Opened 2024-11-28 20:14 UTC by didimitrie

See linear tix for details: we now invalidate all objects whose material property has changed, eg. color: 

https://github.com/user-attachments/assets/d048e722-4916-4304-8299-161157fcd509

2024-11-28 20:18 UTC, oguzhankoral requested changes

2024-11-28 20:18 UTC, oguzhankoral commented on Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
> +    foreach (var rhinoObject in RhinoDoc.ActiveDoc.Objects)
i would iterate all objects only if `ChangedMaterialIndexes` has any

2024-11-28 20:59 UTC, didimitrie commented on Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
> +    foreach (var rhinoObject in RhinoDoc.ActiveDoc.Objects)
True, will do tomorrow!

2024-11-29 08:57 UTC, didimitrie commented on Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
> +    foreach (var rhinoObject in RhinoDoc.ActiveDoc.Objects)
done!

2024-11-29 08:58 UTC, oguzhankoral approved these changes

2024-11-29 09:02 UTC, merged