Fix for Autocad receive speed
specklesystems/speckle-sharp-connectors pull request #424
Opened 2024-11-29 13:54 UTC by adamhathcock

There's no way around having to yield to the UI thread to get a status update.  However, we can reduce the number of times we do so.  This is a quick way to have some updates (factor of 50 reduction) but we could do something more inteligent.

Event binding should be reviewing.  This reduces the allocations of the exception handler tasks.  Needs further work though.

2024-11-29 14:44 UTC, oguzhankoral requested changes

2024-11-29 14:44 UTC, oguzhankoral commented on Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBaseBinding.cs
> +    _idleManager.SubscribeToIdle(
very confused, why we need to subscribe to idle on constructor? Also isn't this PR receive fix, why we are touching send?

2024-11-29 14:44 UTC, oguzhankoral commented on Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs
> +      if (count % 50 == 0)
don't we have debouncing already for this?

2024-12-02 15:05 UTC, JR-Morgan approved these changes

2024-12-02 15:52 UTC, oguzhankoral approved these changes

2024-12-02 15:52 UTC, merged