dui3-175 Direct Shape conversion to native
specklesystems/speckle-sharp-connectors pull request #8
Opened 2024-07-05 21:51 UTC by connorivy

## Description & motivation

## Changes:

### Helpers
- ParameterValueSetter
  - Existing utility so translate base object parameters into Revit object parameters without knowing exactly what parameters are being set
- Revit Categories
  - Removed a bunch of code that wasn't being used and added methods to get the revitCategory from an object.
    - I think this is grasshopper specific

### Converters
- All added converters are exising 'ToNative' methods in the current converter that have been slightly modified to remove redundant try catchs and change code styles

## To-do before merge:

## Screenshots:

![image](https://github.com/specklesystems/speckle-sharp-connectors/assets/43247197/c365f8a7-5866-45ae-a4b4-b3236c7bc4bb)
Finished product, rhino meshes in Revit

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-07-08 13:04 UTC, oguzhankoral requested changes
For now minor comments, will test in 2h

2024-07-08 18:29 UTC, connorivy commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitCategories.cs
> +  public static RevitCategory GetSchemaBuilderCategoryFromBuiltIn(string builtInCategory)
we don't need it as static, but the method has nothing to do with the state in the class, so why not make it static? It saves us from having to make an instance of the Revit Categories class

2024-07-08 18:30 UTC, connorivy commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueSetter.cs
> +  private static string GetParamInternalName(DB.Parameter rp)
you're correct that it isn't necessary, but why does it matter? If you don't make it static, then your IDE will give you a suggestion that the method could be made static

2024-07-09 06:02 UTC, oguzhankoral commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueSetter.cs
> +  private static string GetParamInternalName(DB.Parameter rp)
Wasn't it a compromise we took with DI, use static only if it is reaaly needed? cc @BovineOx

2024-07-09 07:23 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueSetter.cs
> +  private static string GetParamInternalName(DB.Parameter rp)
static private methods are fine.  It's making things not testable that is the issue.  static private stuff is usually tested by testing something else that is instance based and public

2024-07-09 07:24 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitCategories.cs
> +  public static RevitCategory GetSchemaBuilderCategoryFromBuiltIn(string builtInCategory)
we want things to be testable.  A user of this static method can't have it's usage mocked away.  It's best to have a constructor injected logic class that can be tested separately.

2024-07-09 22:04 UTC, connorivy commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitCategories.cs
> +  public static RevitCategory GetSchemaBuilderCategoryFromBuiltIn(string builtInCategory)
these methods are purely utility methods that parse Speckle enums from strings. They don't involve Revit types. Do we need to mock that?

2024-07-10 08:15 UTC, adamhathcock commented on Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitCategories.cs
> +  public static RevitCategory GetSchemaBuilderCategoryFromBuiltIn(string builtInCategory)
we should test all we can...that usually means Mock.

We should especially test utility methods

2024-07-11 07:18 UTC, adamhathcock approved these changes

2024-07-11 12:48 UTC, adamhathcock approved these changes

2024-07-11 13:06 UTC, oguzhankoral approved these changes

2024-07-11 13:34 UTC, merged